const productosShopPage = [
  {
    id: 12,
    nombre: "Luxury Gems Necklace",
    codigo: "N0123",
    precioUnitario: 168.76,
    tipoAccesorio: "Necklace",
    imagenes: "../images/Luxury Gems Necklace.png",
    descripcion: "Collar gema rosada",
    cantidadColor: {
      "Rose Gold": 0,
      Silver: 0,
      Gold: 0,
    },
    cantidadTalla: {
      48: 0,
      50: 0,
      52: 0,
      54: 0,
      56: 0,
      58: 0,
      60: 0,
      62: 0,
      64: 0,
      66: 0,
      68: 0,
      70: 0,
    },
  },
  {
    id: 1,
    nombre: "Aurora Ring",
    codigo: "AN123",
    precioUnitario: 125.28,
    tipoAccesorio: "anillo",
    imagenes: "../images/Aurora Ring.png",
    descripcion: "Anillo diamantado olas",
    cantidadColor: {
      "Rose Gold": 31,
      Silver: 38,
    },
    cantidadTalla: {
      48: 3,
      50: 7,
      52: 0,
      54: 6,
      56: 2,
      58: 9,
      60: 10,
      62: 4,
      64: 15,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 13,
    nombre: "Reflections Necklace",
    codigo: "N0124",
    precioUnitario: 620.73,
    tipoAccesorio: "Necklace",
    imagenes: "../images/Reflections Necklace.png",
    descripcion: "Collar serpiente rojo-negro-dorado",
    cantidadColor: {
      "Rose Gold": 0,
      Silver: 0,
      Gold: 0,
    },
  },
  {
    id: 2,
    nombre: "Dreamy Infinity Ring",
    codigo: "AN124",
    precioUnitario: 327.71,
    tipoAccesorio: "anillo",
    imagenes: "../images/Dreamy Infinity Ring.png",
    descripcion: "Anillo diamante rosa",
    cantidadColor: {
      "Rose Gold": 40,
      Silver: 18,
    },
    cantidadTalla: {
      48: 4,
      50: 7,
      52: 0,
      54: 0,
      56: 5,
      58: 10,
      60: 10,
      62: 4,
      64: 5,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 3,
    nombre: "Opulent Jewels Ring",
    codigo: "AN125",
    precioUnitario: 168.76,
    tipoAccesorio: "anillo",
    imagenes: "../images/Opulent Jewels Ring.png",
    descripcion: "Anillo gato",
    cantidadColor: {
      "Rose Gold": 31,
      Silver: 38,
    },
    cantidadTalla: {
      48: 3,
      50: 7,
      52: 0,
      54: 6,
      56: 2,
      58: 9,
      60: 10,
      62: 4,
      64: 15,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 29,
    nombre: "Serene Solitaire Earrings",
    codigo: "AR124",
    precioUnitario: 620.73,
    tipoAccesorio: "aretes",
    imagenes: "../images/Timeless Halo Earrings.png",
    descripcion: "Aretes crital cuadrado",
    cantidadColor: {
      Gold: 2,
      Silver: 18,
    },
    cantidadTalla: {
      48: 2,
      50: 0,
      52: 2,
      54: 2,
      56: 2,
      58: 2,
      60: 2,
      62: 0,
      64: 2,
      66: 2,
      68: 2,
      70: 2,
    },
  },
  {
    id: 29,
    nombre: "Serene Solitaire Earrings",
    codigo: "AR124",
    precioUnitario: 620.73,
    tipoAccesorio: "aretes",
    imagenes: "../images/Timeless Halo Earrings.png",
    descripcion: "Aretes crital cuadrado",
    cantidadColor: {
      Gold: 2,
      Silver: 18,
    },
    cantidadTalla: {
      48: 2,
      50: 0,
      52: 2,
      54: 2,
      56: 2,
      58: 2,
      60: 2,
      62: 0,
      64: 2,
      66: 2,
      68: 2,
      70: 2,
    },
  },
  {
    id: 20,
    nombre: "Exquisite Earrings",
    codigo: "AR125",
    precioUnitario: 620.73,
    tipoAccesorio: "aretes",
    imagenes: "../images/Exquisite Earrings.png",
    descripcion: "Aretes gota de agua tallados",
    cantidadColor: {
      Gold: 9,
      Silver: 11,
    },
    cantidadTalla: {
      48: 2,
      50: 0,
      52: 2,
      54: 2,
      56: 2,
      58: 2,
      60: 2,
      62: 0,
      64: 2,
      66: 2,
      68: 2,
      70: 2,
    },
  },
  {
    id: 4,
    nombre: "Timeless Elegance Ring",
    codigo: "AN126",
    precioUnitario: 125.28,
    tipoAccesorio: "anillo",
    imagenes: "../images/Timeless Elegance Ring.png",
    descripcion: "3 en 1 lila",
    cantidadColor: {
      "Rose Gold": 40,
      Silver: 18,
    },
    cantidadTalla: {
      48: 4,
      50: 7,
      52: 0,
      54: 0,
      56: 5,
      58: 10,
      60: 10,
      62: 4,
      64: 5,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 20,
    nombre: "Exquisite Earrings",
    codigo: "AR125",
    precioUnitario: 620.73,
    tipoAccesorio: "aretes",
    imagenes: "../images/Exquisite Earrings.png",
    descripcion: "Aretes gota de agua tallados",
    cantidadColor: {
      Gold: 9,
      Silver: 11,
    },
    cantidadTalla: {
      48: 2,
      50: 0,
      52: 2,
      54: 2,
      56: 2,
      58: 2,
      60: 2,
      62: 0,
      64: 2,
      66: 2,
      68: 2,
      70: 2,
    },
  },
  {
    id: 6,
    nombre: "Blissful Bloom Ring",
    codigo: "AN128",
    precioUnitario: 620.73,
    tipoAccesorio: "anillo",
    imagenes: "../images/Blissful Bloom Ring.png",
    descripcion: "Anillo hojas",
    cantidadColor: {
      "Rose Gold": 40,
      Silver: 18,
    },
    cantidadTalla: {
      48: 4,
      50: 7,
      52: 0,
      54: 0,
      56: 5,
      58: 10,
      60: 10,
      62: 4,
      64: 5,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 7,
    nombre: "Sparkling Ring",
    codigo: "AN129",
    precioUnitario: 620.73,
    tipoAccesorio: "anillo",
    imagenes: "../images/Sparkling Ring.png",
    descripcion: "Anillo redondo diamantado",
    cantidadColor: {
      "Rose Gold": 31,
      Silver: 38,
    },
    cantidadTalla: {
      48: 3,
      50: 7,
      52: 0,
      54: 6,
      56: 2,
      58: 9,
      60: 10,
      62: 4,
      64: 15,
      66: 5,
      68: 2,
      70: 6,
    },
  },
  {
    id: 8,
    nombre: "Glimmering Ring",
    codigo: "AN130",
    precioUnitario: 620.73,
    tipoAccesorio: "anillo",
    imagenes: ".../images/Glimmering Ring.png",
    descripcion: "Anillo diamantado encadenado",
    cantidadColor: {
      "Rose Gold": 40,
      Silver: 18,
    },
    cantidadTalla: {
      48: 4,
      50: 7,
      52: 0,
      54: 0,
      56: 5,
      58: 10,
      60: 10,
      62: 4,
      64: 5,
      66: 5,
      68: 2,
      70: 6,
    },
  },
];

const mostrarProducto = (contenedor, listaProductos) =>{
    contenedor.innerHTML = "";
    listaProductos.array.forEach(producto => {
        contenedor.innerHTML
    });
}
